version: '3'

networks:
  laravel-dockerized:

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - laravel-dockerized
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web:/web
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"

  php: 
    container_name: php
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./web:/web
    networks:
      - laravel-dockerized

  mysql: 
    image: mysql:latest
    container_name: mysql
    networks:
      - laravel-dockerized
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    ports:
      - 33601:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

  pma:
    image: phpmyadmin:5.1
    container_name: phpmyadmin
    links:
      - mysql
    networks:
      - laravel-dockerized
    environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: password
        PMA_ARBITRARY: 1
    depends_on:
      - mysql
    ports:
      - 8888:80
    restart: always
