version: '3'

networks:
  laravel-dockerized:

services:

	nginx:
		image: nginx:latest
		container_name: nginx
		networks:
			- laravel-dockerized
		volumes:
			- ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
			- ./web:/web
		depends_on:
			- php
			- mysql
		ports:
			- "8080:80"

	php: 
		container_name: php
		builds: 
			context: .
			dockerfile: Dockerfile
		volumes:
			- ./web:/web
		networks:
			- laravel-dockerized
	
	mysql: 
		image: mysql:latest
		container_name: mysql
		networks:
			- laravel-dockerized
		volumes:
			- ./mysql:/var/lib/mysql
			- ./conf/my.sql:/etc/mysql/my.cnf